let critters = {"agrias butterfly": false,
"ant": true,
"atlas moth": false,
"bagworm": false,
"banded dragonfly": false,
"bell cricket": false,
"blue weevil beetle": false,
"brown cicada": false,
"centipede": false,
"cicada shell": false,
"citrus long-horned beetle": false,
"common bluebottle": false,
"common butterfly": false,
"cricket": false,
"cyclommatus stag": false,
"damselfly": false,
"darner dragonfly": false,
"diving beetle": false,
"drone beetle": false,
"dung beetle": false,
"earth-boring dung beetle": false,
"emperor butterfly": false,
"evening cicada": false,
"firefly": false,
"flea": false,
"fly": false,
"giant cicada": false,
"giant stag": false,
"giant water bug": false,
"giraffe stag": false,
"golden stag": false,
"goliath beetle": false,
"grasshopper": false,
"great purple emperor": false,
"hermit crab": false,
"honeybee": false,
"horned atlas": false,
"horned dynastid": false,
"horned elephant": false,
"horned hercules": false,
"jewel beetle": false,
"ladybug": false,
"long locust": false,
"madagascan sunset moth": false,
"man-faced stink bug": false,
"mantis": false,
"migratory locust": false,
"miyama stag": false,
"mole cricket": false,
"monarch butterfly": false,
"mosquito": false,
"moth": false,
"orchid mantis": false,
"paper kite butterfly": false,
"peacock butterfly": false,
"pill bug": false,
"pondskater": false,
"queen alexandras birdwing": false,
"rainbow stag": false,
"rajah brookes birdwing": false,
"red dragonfly": false,
"rice grasshopper": false,
"robust cicada": false,
"rosalia batesi beetle": false,
"saw stag": false,
"scarab beetle": false,
"scorpion": false,
"snail": false,
"spider": false,
"stinkbug": false,
"tarantula": false,
"tiger beetle": false,
"tiger butterfly": false,
"violin beetle": false,
"walker cicada": false,
"walking leaf": false,
"walking stick": false,
"wasp": false,
"wharf roach": false,
"yellow butterfly": false,
"anchovy": false,
"angelfish": false,
"arapaima": false,
"arowana": false,
"barred knifejaw": false,
"barreleye": false,
"betta": false,
"bitterling": false,
"black bass": false,
"blowfish": false,
"blue marlin": false,
"bluegill": false,
"butterfly fish": false,
"carp": false,
"catfish": false,
"char": false,
"cherry salmon": false,
"clownfish": false,
"coelacanth": false,
"crawfish": false,
"crucian carp": false,
"dab": false,
"dace": false,
"dorado": false,
"football fish": false,
"freshwater goby": false,
"frog": false,
"gar": false,
"giant snakehead": false,
"giant trevally": false,
"golden trout": false,
"goldfish": false,
"great white shark": false,
"guppy": false,
"hammerhead shark": false,
"horse mackerel": false,
"killifish": false,
"king salmon": false,
"koi": false,
"loach": false,
"mahi-mahi": false,
"mitten crab": false,
"moray eel": false,
"napoleon fish": false,
"neon tetra": false,
"nibble fish": false,
"oarfish": false,
"ocean sunfish": false,
"olive flounder": false,
"pale chub": false,
"pike": false,
"piranha": false,
"pond smelt": false,
"pop-eyed goldfish": false,
"puffer fish": false,
"rainbowfish": false,
"ranchu goldfish": false,
"ray": false,
"red snapper": false,
"ribbon eel": false,
"saddled bichir": false,
"salmon": false,
"saw shark": false,
"sea bass": false,
"sea butterfly": false,
"seahorse": false,
"snapping turtle": false,
"soft-shelled turtle": false,
"squid": false,
"stringfish": false,
"sturgeon": false,
"suckerfish": false,
"surgeonfish": false,
"sweetfish": false,
"tadpole": false,
"tilapia": false,
"tuna": false,
"whale shark": false,
"yellow perch": false,
"zebra turkeyfish": false}

export default critters;
